### ISSUE TITLE
Bug re-appeared: Backend layout partially corrupted for non admin users

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/Tag-Groups#36] opened 2023-03-06 15:41 UTC
I think this one slipped back in with the 2.0 release
https://secure.helpscout.net/conversation/2054091939/170427?folderId=4410099

**Comment by ojopaul** [comment] 2023-03-06 16:50
I can confirm the issue is fixed in 2.0. It's probably an issue with freemius version as the only update we provided there is sidebar banner and migration notice. @stevejburge

**Closed** 2023-03-10 17:18 UTC
Labels: bug
