### ISSUE TITLE
Language files are not accurate

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/Tag-Groups#61] opened 2023-04-07 13:04 UTC
Via @wocmultimedia

> I go on checking and translating. Let me know about Tag Groups pro which have the same file .pot of Free version which has 194 strings, completely different of the WP translation system which have 425 strings. Please, have a look at the file pot of both plugins and refresh them. Meanwhile I will make the translation from WP translation system.

**Comment by ojopaul** [comment] 2023-04-10 08:35
@stevejburge premium translation is inside premium/languages

**Comment by wocmultimedia** [comment] 2023-04-10 08:55
Hi,
I checked and it's true that inside the premium folder there's another languages folder but the problem persists. If I open in PoEdit the file tag-groups-premium.pot  which has 166 strings and right-click to check the code occurrence, I get the warning **Source code not found**
See shot below, the same happen if I use the file pot inside the free tag-groups which has 194 strings. Instead if I download the po file from [WP translate system](https://translate.wordpress.org/projects/wp-plugins/tag-groups/stable/it/default/) it has 425 strings and there's full correspondence with source code. 
Something wrong should be between the two local files pot either free or premium version
This is what I experience.
![image](https://user-images.githubusercontent.com/2352240/230868530-41d1ccbb-c4bd-4c6a-8705-b37491fd9595.png)
![image](https://user-images.githubusercontent.com/2352240/230868570-3ea4f1d3-9ae3-4f13-bf4e-edba3affc10d.png)

I put off translating till you don't clarify this issue
Thanks

**Comment by wocmultimedia** [comment] 2023-04-10 10:26
@ojopaul I don't believe it because the problem is that also in free version there'e no correspondence between the actual file.pot and the plugin source code. How I stated there's correspondance in the free version only with the language file.po downloaded from WP system. If do you make a quick check you can see that local Free version has 194 strings/voices while the WP system file has 425. 
The local file pot is not compatible with the plugin ad we talk about the very same version 2.0.1

**Comment by ojopaul** [comment] 2023-04-10 10:45
@wocmultimedia 

What other proposal do you have aside the following?

- Update plugin language pot to latest changes
- Move pro languages from /premium/languages/ to /language/ (This means both free and pro language will be inside same folder for pro version)

**Comment by wocmultimedia** [comment] 2023-04-10 10:55
I think these two solutions are fine. Just check what's wrong between the pot file inside the actual plugin and the po file on WP system. I suggest this to avoid it repeating again in the future. I mean better investigate to whose plugin belongs the local file pot which is completely different.
Then you can proceed to your solutions

**Comment by ojopaul** [comment] 2023-04-10 13:47
@wocmultimedia On  
`"Just check what's wrong between the pot file inside the actual plugin and the po file on WP system. "`

Nothing we can do from plugin end other than making sure the strings inside the plugin at the point of release is up to date.

I believe we already had this discussion on WP system in relationship to how they sync translation changes and what file to translate and that should do.

**Comment by wocmultimedia** [comment] 2023-04-10 14:11
@ojopaul Yes, but at that time of Author there were correspondence but not now. This is the problem. If I translate the 194 strings inside the free version no on line I can check in the plugin because no translation will appear. That's the problem. The actual file pot inside the plugin folder isn't compatible with the plugin itself.

**Comment by ojopaul** [comment] 2023-04-10 14:24
Okay @wocmultimedia 

That's why I said I'm opened to discussion or suggestion on this issue.

I'm a developer and you're translator. You may know better ways on how things are done in relation to this issue.

I accept a primary responsibility to make sure every new release contain updated strings including removing strings that no longer exist in the plugin while adding new one.

So, what else do you want me to do?

**Comment by wocmultimedia** [comment] 2023-04-10 14:32
Hi @ojopaul ,
I think that you can make a simple test. Make a new file pot from the plugin code latest version. Then try to open it in PoEdit and right click on whatever line to check if there's Source code occurence, If not something is wrong in the way you get the file pot.
IMHO there's no other way. Because I can translate what do you give me and I don't know from where the file comes, I'm not a developer at all

**Comment by ojopaul** [comment] 2023-04-10 14:40
@wocmultimedia Let come back to this after next release.

But I need you to know wordpress doesn't provide avenue to update translation file separately after a new release.

If after new release, wordpress doesn't synch the translation on time, it's totally out our issue to fix but i hope things work out after next release as I'll make sure the plugin itself contain updated file.

**Comment by wocmultimedia** [comment] 2023-04-10 14:48
@ojopaul As I wrote before the problem is only that the WP file corresponds with the current v 2.0.1 plugin but not the local file pot. 
Referring to WP system they sync the file you supply at the same time they declare available the new version. 
When do you have the release ready please, send me the file before you publish it. I make a new check or send me now a new file pot as you usually create it. I will make a new check with this 2.0.1 just to make a double test  Otherwise we never get rid of this problem

**Comment by wocmultimedia** [comment] 2023-04-10 16:40
@ojopaul Please have a look at these 4 shots. I activated the Free version 2.0.1 of Tags Groups. Selected a string from the Tools Section and made a search 

1. First in the local file pot supplied with the plugin (194 strings) no string found
2.  then with the file downloaded from WP (425 strings) - 1 string found
3. then with the German translation inside the D:\Bitnami\wordpress-5.5.3-0\apps\wordpress\htdocs\wp-content\languages\plugins\tag-groups-de_DE.po (310 strings) - 1 string found
**SHOT 1 - STRING SEARCHED**
![String_Searched](https://user-images.githubusercontent.com/2352240/230947219-fb4e8594-0193-4ffb-9d80-0ddf52920600.jpg)

**SHOT 2 - FILE POT SUPPLIED WITH PLUGIN**
![Local_no_results](https://user-images.githubusercontent.com/2352240/230947321-5c5ded74-4dbf-43ff-9b33-ede7aee606b0.jpg)

**SHOT 3 - FILE IT DOWNLOADED FROM WP**
![Result_File_from_WP](https://user-images.githubusercontent.com/2352240/230947546-21af767c-da9e-4292-9540-a5ff3801731a.jpg)

**SHOT 4 - GERMAN TRANSLATION**
![German_file_search](https://user-images.githubusercontent.com/2352240/230947640-8eb1a89a-1d0f-4c24-be22-1758983c0254.jpg)

I suggest we can make the Italian, French and Spanish translation from the WP Italian (425 strings) because the German (310 strings) is shown on WP  as 93% translated.

The problem is the strange .pot file supplied with the plugin

**Comment by ojopaul** [comment] 2023-04-10 16:44
@wocmultimedia 
 
I thought Steve sent 2.0.2 to you or you mean you're testing with 2.0.2?

**Comment by wocmultimedia** [comment] 2023-04-10 18:50
Hi @ojopaul , @stevejburge , 
The file pot of the new release supplied me works fine with the version 2.9.1 too. I will start translating tomorrow. Meanwhile see shot below of Italian test
![Test-positive-IT](https://user-images.githubusercontent.com/2352240/230972099-e0c2618f-1665-4b9d-ab2e-73b1f0feed74.jpg)

Thanks for the very great cooperation we can develop together

**Comment by wocmultimedia** [comment] 2023-04-12 09:14
Hi @stevejburge , @ojopaul 
I translated in Italian the tag-groups.pot file related to Tag Groups free plugin supplied by Steve which you find here below. 
[tag-groups_Free-ITALIAN.zip](https://github.com/TaxoPress/Tag-Groups/files/11209417/tag-groups_Free-ITALIAN.zip)

But after uploading it to WP systems it appears there are still 115 strings untranslated. Please, see shot below.
Why don't we use this WP file for the free version to avoid of having conflict instead of the one supplied by you? Because I saw that some more parts of the free plugin are not translated using the file pot I just translated now.
![image](https://user-images.githubusercontent.com/2352240/231411876-748822b2-669b-49d9-9bf2-df0e357635ea.png)

**Comment by stevejburge** [comment] 2023-04-12 11:58
@wocmultimedia I had problems getting these files to load and test

<img width="1160" alt="Screenshot 2023-04-12 at 7 57 37 AM" src="https://user-images.githubusercontent.com/3868028/231450136-6e0e7ee7-eb50-478d-b54c-a928561a2cc2.png">
<img width="705" alt="Screenshot 2023-04-12 at 7 58 37 AM" src="https://user-images.githubusercontent.com/3868028/231450208-8b82f73e-bc14-4b2c-a486-dcf3d539f0c7.png">

**Comment by wocmultimedia** [comment] 2023-04-12 12:22
To test this file you must switch your site to Italian or your profile to Italian, otherwise cannot check it, obviously

**Comment by stevejburge** [comment] 2023-04-12 12:39
@wocmultimedia Ah, yes. It worked in the main /languages/ folder

This seems to be translated except the header, footer, and sidebar

<img width="1343" alt="Screenshot 2023-04-12 at 8 38 47 AM" src="https://user-images.githubusercontent.com/3868028/231459836-827c955d-e528-4fd5-8365-173e46a51346.png">

**Comment by wocmultimedia** [comment] 2023-04-12 14:24
I made a check related the picture shown in your message and these strings are found within the WP file

- Enhance the power of Tag Groups with the Pro version:
- If you need help or have a new feature request, let us know
- [Request Support](https://wordpress.org/support/plugin/tag-groups/)
- [View Knowledge Base](https://taxopress.com/docs/)

These no: 
You're using Tag Groups Free. The Pro version has more features and support.
If you like Tag Groups, I would be very happy if you could give it a [★★★★★](https://wordpress.org/support/plugin/tag-groups/reviews?filter=5&rate=5#new-post) rating. Thank you very much in advance!
Detailed documentation is also available on the plugin website.

By the end most of the missing part is within the WP file to be downloaded from the system, while others are still missing.

**Comment by ojopaul** [comment] 2023-04-12 14:34
@wocmultimedia We can't download the wordpress.org version because it'll always be outdated.

1. We haven't release 2.0.2 yet, and that explains why some strings are missing on the plugin while they exist on wordpress.org version. For example, we already removed  "You're using Tag Groups Free. The Pro version has more features and support.
If you like Tag Groups, I would be very happy if you could give it a [★★★★★](https://wordpress.org/support/plugin/tag-groups/reviews?filter=5&rate=5#new-post) rating. Thank you very much in advance!
Detailed documentation is also available on the plugin website."

**Comment by wocmultimedia** [comment] 2023-04-12 14:44
So no problem, indeed.
I will go on translating the file supplied.
Thanks a lot to make me understood the real situation. Now, I think it's clear.
I proceed with the Premium but let me tell you one thing Why do you call the folder tag-groups-pro and inside the file pot is called in two different way Pro and Premium? Doesn't it make confusion to the user? Have a look at the shot
![pro-premium](https://user-images.githubusercontent.com/2352240/231493977-83f38a34-1501-4625-a733-d8142cc88057.jpg)

**Comment by wocmultimedia** [comment] 2023-04-12 16:39
I don't know where to look for log . Yes, the free is deactivated. I also tested with the whole other plugins deactivated

**Comment by ojopaul** [comment] 2023-04-12 17:27
@wocmultimedia @stevejburge will send updated version to you. FYI, it has updated strings for both free and pro version and also make translation work without the need to copy it to wordpress language folder

**Comment by wocmultimedia** [comment] 2023-04-13 09:21
Any news about this update?

**Comment by stevejburge** [comment] 2023-04-13 17:44
@wocmultimedia Can you check version 2.0.2 which is out now?

**Comment by wocmultimedia** [comment] 2023-04-13 17:51
is this the Free version or the Pro one? Because the crash problem was with the Pro one

**Comment by stevejburge** [comment] 2023-04-13 18:00
I'm testing Tag Groups 2.0.2 Free...

- Italian: complete except for header, footer, sidebar
- Spanish: not done
- French: not done

I'm testing Tag Groups 2.0.2 Pro..

- Italian: complete except for header, footer, sidebar, and also some Pro features. I've attached a screenshot
- Spanish: not done
- French: not done

<img width="706" alt="Screenshot 2023-04-13 at 2 00 17 PM" src="https://user-images.githubusercontent.com/3868028/231845090-be7a2478-7749-465e-b810-cfdc72429e0a.png">

**Comment by wocmultimedia** [comment] 2023-04-13 18:05
I installed the 2.02. I tried to remove the IT translation from the main WP folder and it works. I also searched and found for the header "You're using...". I translated and here's the shot
![image](https://user-images.githubusercontent.com/2352240/231845963-11b1f42f-2c2f-49b2-8496-ce685d611ac0.png)

**Comment by wocmultimedia** [comment] 2023-04-14 10:53
Hi @ojopaul , @stevejburge 

Here's the Italian Translation Updates of both. Please use these translations which I double checked.
**Free**
[ITALIAN_Translation2.0.2.zip](https://github.com/TaxoPress/Tag-Groups/files/11231965/ITALIAN_Translation2.0.2.zip)

**PRO**
[Tag_Groups_PRO-ItalianTranslation.zip](https://github.com/TaxoPress/Tag-Groups/files/11231968/Tag_Groups_PRO-ItalianTranslation.zip)

Translation is complete but about 2% has no reference strings as shown in shots below

![Backend-no-ref1](https://user-images.githubusercontent.com/2352240/232025366-ff542a5a-abee-4c5a-ae1c-d4951ab3c9a2.jpg)
![Frontend-no-ref1](https://user-images.githubusercontent.com/2352240/232025374-01358256-751b-4e49-a571-54b603b2db5b.jpg)
![Frontend-no-ref2](https://user-images.githubusercontent.com/2352240/232025377-38333874-2b4b-4d2f-b2f2-0b8c64f9fb85.jpg)
![WIzard_No_Reference1](https://user-images.githubusercontent.com/2352240/232025378-3c146c32-210d-4099-884a-3ea709fcb0a4.jpg)
![WIzard_No_Reference2](https://user-images.githubusercontent.com/2352240/232025383-e982f1ce-e7bc-4e44-9714-e3e7e8cc254d.jpg)
![WIzard_No_Reference3](https://user-images.githubusercontent.com/2352240/232025389-3266a081-4431-4d17-9ccb-5ed7c636e7e1.jpg)

**Comment by ojopaul** [comment] 2023-05-18 12:17
@stevejburge @wocmultimedia Please open new issue and add to active milestone if there's a new problem with translation.

The main reason for opening this issue has been fixed and the conversation here is too long making it difficult to know if it's been moved to new milestone due to new issue or not.

**Closed by ojopaul** 2023-05-18 12:17 UTC
Labels: bug
